const API="https://api.open-meteo.com/v1/forecast";
const GEO="https://geocoding-api.open-meteo.com/v1/search";
const $=id=>document.getElementById(id);
let coords={lat:18.5204,lon:73.8567,name:"Pune",country:"India"};
const weatherMap={0:["Clear sky","☀️","clear","Sheepy is soaking up the sun ☀️"],1:["Mainly clear","🌤️","clear","A perfect little sun nap 🌤️"],2:["Partly cloudy","⛅","cloud","Sheepy found a cozy patch of shade ⛅"],3:["Overcast","☁️","cloud","Cloudy, but still meadow-worthy ☁️"],45:["Foggy","🌫️","cloud","Sheepy says: visibility is overrated 🌫️"],48:["Foggy","🌫️","cloud","A mysterious morning for Sheepy 🌫️"],51:["Light drizzle","🌦️","rain","Sheepy is heading under the tree 🌦️"],53:["Drizzle","🌦️","rain","Tiny drops! Shelter time, Sheepy 🌦️"],55:["Heavy drizzle","🌧️","rain","Definitely a tree day 🌧️"],61:["Light rain","🌧️","rain","Rain! Sheepy is hiding under the tree 🌧️"],63:["Rain","🌧️","rain","Sheepy found a dry shelter 🌧️"],65:["Heavy rain","🌧️","rain","Sheepy is staying VERY fluffy and dry 🌧️"],71:["Light snow","🌨️","rain","Sheepy has never seen this much fluff 🌨️"],73:["Snow","❄️","rain","Sheepy is bundled up ❄️"],75:["Heavy snow","❄️","rain","Sheepy votes for a warm barn ❄️"],80:["Rain showers","🌦️","rain","Quick! Back under the tree 🌦️"],81:["Rain showers","🌧️","rain","Sheepy is sheltering from showers 🌧️"],82:["Heavy showers","⛈️","rain","Sheepy is waiting this one out ⛈️"],95:["Thunderstorm","⛈️","rain","Nope. Sheepy is absolutely under the tree ⛈️"],96:["Thunderstorm","⛈️","rain","Sheepy says: stay cozy indoors ⛈️"],99:["Thunderstorm","⛈️","rain","Sheepy is hiding from the storm ⛈️"]};
const dayNames=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
function setWeather(code,isDay=true){const [label,icon,state,msg]=weatherMap[code]||weatherMap[0];document.body.dataset.weather=isDay?state:"night";$('condition').textContent=`${icon} ${label}`;$('mood').textContent=state==='rain'?"TREE SHELTER":state==='cloud'?"CLOUD WATCHER":isDay?"SUNNY SHEEP":"NIGHT NAPPER";$('weatherBubble').textContent=isDay?msg:"Sheepy is tucked in for the night 🌙";$('sheepStage').setAttribute('aria-label',`${label}. ${isDay?msg:"Sheepy is tucked in for the night."}`);return{label,icon,state}}
function fmtTime(iso){return new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit"}).format(new Date(iso))}
function showToast(text){$('toast').textContent=text;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2800)}
async function loadWeather(){try{$('updated').textContent="Fetching the latest sky…";const url=`${API}?latitude=${coords.lat}&longitude=${coords.lon}&current=temperature_2m,relative_humidity_2m,apparent_temperature,is_day,precipitation,rain,weather_code,wind_speed_10m,wind_direction_10m&hourly=precipitation_probability&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&forecast_days=5&timezone=auto`;const d=await fetch(url).then(r=>{if(!r.ok)throw Error();return r.json()});const c=d.current;$('place').textContent=`${coords.name}${coords.country?`, ${coords.country}`:""}`;$('updated').textContent=`Updated ${fmtTime(c.time)}`;$('temp').textContent=`${Math.round(c.temperature_2m)}°`;$('feels').textContent=`Feels like ${Math.round(c.apparent_temperature)}°`;$('humidity').textContent=`${Math.round(c.relative_humidity_2m)}%`;$('wind').textContent=`${Math.round(c.wind_speed_10m)} km/h`;$('windDir').textContent=`${windDirection(c.wind_direction_10m)} wind`;$('rainChance').textContent=`${d.hourly.precipitation_probability?.[0]??d.daily.precipitation_probability_max?.[0]??0}%`;const meta=setWeather(c.weather_code,!!c.is_day);renderForecast(d.daily);document.title=`${meta.label} · Sheepy Weather`}catch(e){$('updated').textContent="Weather service unavailable";showToast("Couldn't reach the weather service. Try again.")}}
function windDirection(deg){const dirs=["N","NE","E","SE","S","SW","W","NW"];return dirs[Math.round(deg/45)%8]}
function renderForecast(d){$('forecast').innerHTML=d.time.map((date,i)=>{const meta=weatherMap[d.weather_code[i]]||weatherMap[0];const day=i===0?"Today":dayNames[new Date(date+"T12:00:00").getDay()];return `<article class="day ${i===0?"today":""}"><div class="day-name">${day}</div><div class="day-icon">${meta[1]}</div><div class="day-temp">${Math.round(d.temperature_2m_max[i])}° <span style="color:#9aa8a1;font-weight:500">${Math.round(d.temperature_2m_min[i])}°</span></div><div class="day-rain">💧 ${d.precipitation_probability_max?.[i]??0}%</div></article>`}).join("")}
async function searchCity(q){if(!q.trim())return;try{const data=await fetch(`${GEO}?name=${encodeURIComponent(q)}&count=5&language=en&format=json`).then(r=>r.json());const list=data.results||[];if(!list.length){showToast("No places found. Try another city.");return}const box=$('suggestions');box.innerHTML=list.map((x,i)=>`<button class="suggestion" data-i="${i}">📍 ${x.name}${x.admin1?`, ${x.admin1}`:""}${x.country?` · ${x.country}`:""}</button>`).join("");box.hidden=false;box.querySelectorAll('.suggestion').forEach(btn=>btn.onclick=()=>{const x=list[+btn.dataset.i];coords={lat:x.latitude,lon:x.longitude,name:x.name,country:x.country};$('cityInput').value=x.name;box.hidden=true;loadWeather()})}catch(e){showToast("Search failed. Check your connection.")}}
$('searchForm').addEventListener('submit',e=>{e.preventDefault();searchCity($('cityInput').value)});$('refreshBtn').onclick=loadWeather;$('locateBtn').onclick=()=>{if(!navigator.geolocation){showToast("Location isn't supported by this browser.");return}navigator.geolocation.getCurrentPosition(async p=>{coords={lat:p.coords.latitude,lon:p.coords.longitude,name:"Your location",country:""};try{const g=await fetch(`${GEO}?latitude=${coords.lat}&longitude=${coords.lon}&count=1&language=en&format=json`).then(r=>r.json());if(g.results?.[0]){coords.name=g.results[0].name;coords.country=g.results[0].country}}catch{}loadWeather()},()=>showToast("Location permission was not granted."))};document.addEventListener('click',e=>{if(!e.target.closest('.search')&&!e.target.closest('.suggestions'))$('suggestions').hidden=true});loadWeather();